# Generated by Django 2.2.16 on 2020-09-06 16:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('test', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(default='Unknown', max_length=50, required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False))])))], null=True),
        ),
    ]
