# Generated by Django 2.2.16 on 2020-11-04 10:31

import contrib.wagtailmath.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(template='home/blocks/rich_text.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('columns', wagtail.core.blocks.StructBlock([('columns', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(template='columns/column_rich_text.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())]))])), ('mathjax', contrib.wagtailmath.blocks.MathjaxBlock()), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('cpp', 'C++'), ('c', 'C'), ('java', 'Java'), ('ocaml', 'OCaml'), ('haskell', 'Haskell'), ('rust', 'Rust'), ('python3', 'Python 3'), ('bash', 'Bash/Shell'), ('javascript', 'Javascript'), ('css', 'CSS'), ('html', 'HTML'), ('julia', 'Julia'), ('nginx', 'Nginx configuration file'), ('numpy', 'NumPy'), ('django', 'Django'), ('jinja', 'Jinja'), ('docker', 'Docker'), ('jinja', 'Jinja'), ('yaml', 'YAML'), ('json', 'JSON'), ('plpgsql', 'PL/pgSQL'), ('psql', 'PostgreSQL console (psql)')], null=False)), ('caption', wagtail.core.blocks.CharBlock(blank=True, nullable=True, required=False)), ('src', wagtail.core.blocks.TextBlock())]))]),
        ),
    ]
