# Generated by Django 2.2.16 on 2020-09-06 16:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200906_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('test', wagtail.core.blocks.StructBlock([('authors', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(default='Unknown', max_length=50, required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False))])))]))], null=True),
        ),
    ]
