# Generated by Django 2.2.16 on 2020-09-06 17:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200906_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(default='Unknown', max_length=50, required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False))]))], null=True),
        ),
    ]
