# Generated by Django 2.2.9 on 2020-01-08 19:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexiblePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=140, null=True)),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            ("rich_text", wagtail.core.blocks.RichTextBlock()),
                            ("raw_html", wagtail.core.blocks.RawHTMLBlock()),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    ("rich_text", wagtail.core.blocks.RichTextBlock()),
                    ("raw_html", wagtail.core.blocks.RawHTMLBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="description",
            field=wagtail.core.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "entry_title",
                    models.CharField(
                        blank=True,
                        help_text="Peut être laissé vide, il sera alors affiché le lien, ou le titre de la page interne",
                        max_length=50,
                        null=True,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "link_external",
                    models.URLField(
                        blank=True,
                        help_text="AJoutez un lien externe ici. Il sera utilisé si aucun lien interne n'est défini.",
                        null=True,
                        verbose_name="Lien externe",
                    ),
                ),
                (
                    "link_internal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ce lien sera utilisé en priorité si défini",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.Page",
                        verbose_name="Lien interne",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="home.HomePage",
                    ),
                ),
            ],
            options={"verbose_name": "Lien",},
        ),
    ]
