# Generated by Django 2.2.9 on 2020-01-08 19:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200108_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="description",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
