# Generated by Django 2.2.9 on 2020-01-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_link_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="description",),
        migrations.RemoveField(model_name="link", name="description",),
    ]
