# Generated by Django 2.2.9 on 2020-01-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200108_2107"),
    ]

    operations = [
        migrations.DeleteModel(name="Link",),
    ]
