# Generated by Django 2.2.16 on 2020-09-06 13:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200904_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
