# Generated by Django 2.2.16 on 2020-11-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201103_1709'),
        ('home', '0010_auto_20201103_1939'),
    ]

    operations = [
    ]
