# Generated by Django 2.2.16 on 2020-11-04 10:31

import contrib.wagtailmath.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_20201104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblepage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(template='home/blocks/rich_text.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('columns', wagtail.core.blocks.StructBlock([('columns', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(template='columns/column_rich_text.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())]))])), ('mathjax', contrib.wagtailmath.blocks.MathjaxBlock()), ('trombinoscope', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=True)), ('position', wagtail.core.blocks.CharBlock(required=True)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('bio', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(template='home/blocks/rich_text.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('columns', wagtail.core.blocks.StructBlock([('columns', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(template='columns/column_rich_text.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())]))])), ('mathjax', contrib.wagtailmath.blocks.MathjaxBlock()), ('trombinoscope', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=True)), ('position', wagtail.core.blocks.CharBlock(required=True)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('bio', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True))])))]))], blank=True, null=True),
        ),
    ]
