# Generated by Django 2.2.18 on 2021-09-16 16:33

import contrib.opengraph.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraphRendition',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('rendered', models.ImageField(height_field='height', upload_to=contrib.opengraph.models.upload_og_image, width_field='width')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenGraphSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_subtitle', models.CharField(max_length=80, verbose_name='Sous-titre par défaut')),
                ('default_bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'paramètres OpenGraph',
                'verbose_name_plural': 'paramètres OpenGraph',
            },
        ),
    ]
