# Generated by Django 2.2.18 on 2021-09-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opengraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opengraphsettings',
            name='default_subtitle',
        ),
    ]
